// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmvuufeeevlufyxgzndx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdnV1ZmVlZXZsdWZ5eGd6bmR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NDkyODUsImV4cCI6MjA2NjIyNTI4NX0.sd9m5ToeY91BZ3BepRr4c7KP1tirC8lHsnPxi18FcxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);